language: c
compiler:
    - gcc
    - clang
script: git clone git@github.com:AlexsJones/jnxlibc.git && cd jnxlibc && ./platforms/linux/ && make && sudo make install && cd ../../../ && make
notifications:
    email:
        recipients:
            - jonesax@hush.com
        on_success: [never]
        on_failure: [always]
